#!/usr/bin/env python3
import sys
from scanamabob.commands import commands

VERSION = '0.0.1'
USAGE = f"""Usage: scanamabob <command> [-h] [command-specific-arguments]

Scanamabob v{VERSION} - AWS Security Tooling

This tool is in a very early phase of development and is undergoing active development. Many desired features are currently missing and incomplete. Early release of this version through PyPI is intended to generate useful feedback from potential users.

  scan     -  Scan AWS environment for common security misconfigurations"""

if len(sys.argv) < 2 or sys.argv[1] not in commands:
    print(USAGE)
    exit(1)

commands[sys.argv[1]]['function'](sys.argv[2:])

