#!/usr/bin/env python3
import sys

from scanamabob.commands import commands
import argparse

VERSION = '0.0.2'
USAGE = f"""Usage: scanamabob <command> [command-specific-arguments]

Scanamabob v{VERSION} - AWS Security Tooling

This tool is in a very early phase of development and is undergoing active development. Many desired features are currently missing and incomplete. Early release of this version through PyPI is intended to generate useful feedback from potential users.

  scan     -  Scan AWS environment for common security misconfigurations
  s3audit  -  Generate report on S3 access controls
\n
"""

main_parser = argparse.ArgumentParser(prog='scanamabob', usage=USAGE, add_help=False)
subparsers = main_parser.add_subparsers(
    prog='scanamabob', dest='command', required=True
)

for cmd in commands.values():
    cmd['add_parser'](subparsers)

args = main_parser.parse_args()
args.func(args)
